version: '3.8'

services:

  db:
    image: "mysql:5.7.32"
    container_name: some-db
    env_file: .env
    volumes: 
      - ./db/volumes/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command: ["mysqld"]
    ports:
      - 3306:3306

  adminer:
    image: "adminer:4.7.7"
    container_name: some-adminer
    ports: 
      - 3307:8080
