version: '3.8'

services:

  db:
    image: "mysql:5.7.32"
    container_name: db
    env_file: .env
    volumes: 
      - ./db/volumes/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command: ["mysqld"]
    expose:
      - 3306

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file: .env
    expose: 
      - 3000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file: .env
    expose:
      - 3000

  webserver:
    container_name: webserver
    build:
      context: ./webserver
    ports:
      - 80:80
      - 443:443
