export const REQUEST_CURRENT_LOCATION = "REQUEST_CURRENT_LOCATION";
export const RESPONSE_CURRENT_LOCATION = "RESPONSE_CURRENT_LOCATION";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";

export default {
  REQUEST_CURRENT_LOCATION,
  RESPONSE_CURRENT_LOCATION,
  CREATE_ORDER,
  UPDATE_ORDER_STATUS,
};
