export const REQUEST_CURRENT_LOCATION = "REQUEST_CURRENT_LOCATION";
export const RESPONSE_CURRENT_LOCATION = "RESPONSE_CURRENT_LOCATION";

export default { REQUEST_CURRENT_LOCATION, RESPONSE_CURRENT_LOCATION };
