export const UPDATE_CURRENT_LOCATION = "UPDATE_CURRENT_LOCATION";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";

export default {
  UPDATE_CURRENT_LOCATION,
  CREATE_ORDER,
  UPDATE_ORDER_STATUS,
};
