type Query {
  me: User
  users(search: String!): [User]
  user(userId: Int!): User
  drivers: [User]
  customers: [User]
  orders: [Order]
  order(orderId: String): Order
}

type Mutation {
  signUp(input: SignUpInput): User!
  signIn(input: SignInInput): User!
  signOut: String

  createOrder(input: CreateOrderInput): Order
  updateOrderStatus(input: UpdateOrderStatusInput): Order

  updateCurrentLocation(input: LatLngInput): CurrentLocation

  responseNewJob(input: ResponseNewJobInput): String
}

type Subscription {
  currentLocationUpdated: CurrentLocation
  orderCreated: Order
  orderStatusUpdated: Order
  newJobRequested(driverId: Int): NewJobRequestedSubscriptionResponse
  newJobResponsed(driverId: Int): NewJobResponsedSubscriptionResponse
}

type NewJobRequestedSubscriptionResponse {
  driverIds: [Int]
  order: Order
  driverRouteMapper: [DriverRouteMapper]
}

type NewJobResponsedSubscriptionResponse {
  driverIds: [Int]
  order: Order
  success: Int
}

type DriverRouteMapper {
  me: User
  polylines: String
  duration: Int
  lastDuration: Int
}

type CurrentLocation {
  at: Float
  latLng: LatLng
  status: String
}

type LatLng {
  latitude: Float
  longitude: Float
}

type User {
  userId: ID
  firstName: String
  lastName: String
  email: String
  username: String
  phone: String
  role: String
  receiveOrders: [Order]
  sendOrders: [Order]
  driverOrders: [Order]
  currentLocation: CurrentLocation
  jobs: [Job]
  currentJobs: [Job]
  createdAt: String
  updatedAt: String
  deletedAt: String
}

type Order {
  orderId: ID!
  creator: User
  sender: User
  sendAddress: String
  sendLatLng: LatLng
  receiver: User
  receiveAddress: String
  receiveLatLng: LatLng
  suggestedPolylines: String
  estimatedDuration: Int
  duration: Int
  status: String
  comments: String
  logs: [OrderLog]
  jobs: [Job]
  createdAt: String
  updatedAt: String
  deletedAt: String
}

type Job {
  jobId: ID!
  driver: User
  order: Order
  status: String
  polylines: String
  duration: Int
}

type OrderLog {
  orderLogId: ID!
  order: Order
  status: String
  comments: String
  createdAt: String
  updatedAt: String
  deletedAt: String
}

input SignUpInput {
  firstName: String!
  lastName: String!
  email: String!
  phone: String
  username: String!
  password: String!
  role: String!
}

input SignInInput {
  username: String!
  password: String!
  role: String!
}

input CreateOrderInput {
  senderId: Int
  receiverId: Int
  sendAddress: String
  sendLatLng: String
  receiveAddress: String
  receiveLatLng: String
}

input UpdateOrderStatusInput {
  orderId: String
  status: String
  comments: String
}

input LatLngInput {
  latitude: Float
  longitude: Float
}

input ResponseNewJobInput {
  duration: Int
  lastDuration: Int
  polylines: String
  orderId: String
}
