type Query {
  me: User
  users(search: String!): [User]
  user(userId: Int!): User
  addresses(userId: Int!): [Address]
  districts: [District]
  coordinates(query: String, county: String): LatLng
  orders(orderSearch: OrderSearch): [Order]
}

type Mutation {
  signUp(input: SignUpInput): User!
  signIn(input: SignInInput): User!
  signOut: String

  addFriend(userId: Int!): User

  createOrder(input: CreateOrderInput): Order
  updateOrderStatus(orderId: String, status: String): Order
}

type District {
  districtId: ID
  name: String
}

type LatLng {
  latitude: Float
  longitude: Float
}

type User {
  userId: ID
  firstName: String
  lastName: String
  email: String
  username: String
  role: String
  avatarUri: String
  depot: Depot
  receiveOrders: [Order]
  sendOrders: [Order]
  deliverOrders: [Order]
  followees: [Follow]
  followers: [Follow]
  addresses: [Address]
  createdAt: String
  updatedAt: String
  deletedAt: String
}

type Follow {
  followerId: Int
  followeeId: Int
  followee: User!
  follower: User!
}

type Depot {
  depotId: Int
  name: String
  district: String
  latitude: Float
  longitude: Float
}

type Order {
  orderId: ID!
  sender: User
  senderAddress: Address
  receiver: User
  receiverAddress: Address
  sendDriver: User
  receiveDriver: User
  sendDepot: Depot
  receiveDepot: Depot
  status: String
  qrcode: String
  comments: String
  logs: [OrderLog]
  createdAt: String
  updatedAt: String
  deletedAt: String
}

type Address {
  addressId: ID
  User: User
  address: String
  district: String
  latitude: Float
  longitude: Float
  createdAt: String
  updatedAt: String
  deletedAt: String
}

type OrderLog {
  orderLogId: ID!
  order: Order
  status: String
  comments: String
  createdAt: String
  updatedAt: String
  deletedAt: String
}

input OrderSearch {
  depotId: ID
  status: String
}

input SignUpInput {
  firstName: String!
  lastName: String!
  email: String!
  username: String!
  password: String!
  role: String!
}

input SignInInput {
  username: String!
  password: String!
  role: String!
}

input CreateOrderInput {
  receiverId: Int
  sendAddressId: Int
  receiveAddressId: Int
}
